#pragma once
//**************************************
// lex.h
//
// Defines global symbols used the the flex generated lexer and 
// bison generated parser.
//
// Author: Phil Howard phil.howard@oit.edu
//

#include "cSymbol.h"
#include "cSymbolTable.h"       // change this name to whatever you call your
                                // public symbol table interface definition file

// lexer function generated by flex
int yylex();

// type for yylval
typedef union
{
    int token;
    cSymbol *symbol;
} yylval_t;

extern yylval_t yylval;     // Semantic value of current token
extern char *yytext;        // text of the current token
extern int yylineno;        // line number of current token
extern FILE *yyin;          // input file for lexer
